version: "3.9"

services:
  db:
    image: postgres:15
    container_name: artsearch-db
    restart: always
    environment:
      POSTGRES_USER: art
      POSTGRES_PASSWORD: artpass
      POSTGRES_DB: artsearch
    volumes:
      - artsearch_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U art -d artsearch"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - art-search-network

  weaviate:
    image: semitechnologies/weaviate:1.27.6
    container_name: artsearch-weaviate
    restart: always
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      ENABLE_MODULES: text2vec-transformers
      TRANSFORMERS_INFERENCE_API: http://t2v-transformers:8080
      CLUSTER_HOSTNAME: node1
    depends_on:
      - t2v-transformers
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://localhost:8080/v1/.well-known/ready || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 90s
    volumes:                      
      - weaviate_data:/var/lib/weaviate

    networks:
      - art-search-network


  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-all-MiniLM-L6-v2
    container_name: t2v-transformers
    environment:
      ENABLE_CUDA: "0"
    networks:
      - art-search-network

  art-search-backend:
    build: .
    container_name: art-search-backend
    depends_on:
      weaviate:
        condition: service_healthy
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://art:artpass@db:5432/artsearch
      WEAVIATE_URL: http://weaviate:8080
    networks:
      - art-search-network
    volumes:
      - .:/app 
      - ./images:/app/images
      - ./data/wikiart:/app/data/wikiart
      - ./data/artworks.db:/app/data/wikiart/artworks.db 
volumes:
  artsearch_data:
  weaviate_data:

networks:
  art-search-network:
    driver: bridge
